--TABLE CREATION
CREATE TABLE MMOHONEY.DUMMY_TABLE_TO_AUDIT
  (
     ID            NUMBER(10) NOT NULL,
     FIRST_NAME    VARCHAR2(100) NOT NULL,
     LAST_NAME     VARCHAR2(100) NOT NULL,
     START_DATE    TIMESTAMP(6) NOT NULL,
     END_DATE      TIMESTAMP(6) NULL,
     IS_SALARY     NUMBER(1) NOT NULL,
     SALARY        NUMBER(19, 4) NULL,
     HOURLY_WAGE   NUMBER(19, 4) NULL,
     INFORMAL_NAME VARCHAR2(250) NULL,
     GENDER        CHAR(1) NOT NULL,
     CREATED_BY    VARCHAR2(45) NOT NULL,
     CREATED_DATE  TIMESTAMP (6) NOT NULL,
     MODIFIED_BY   VARCHAR2(255) NOT NULL,
     MODIFIED_DATE TIMESTAMP (6) NOT NULL
  ); 

--CONTRAINT
ALTER TABLE MMOHONEY.DUMMY_TABLE_TO_AUDIT
  ADD CONSTRAINT DUMMY_TABLE_TO_AUDIT_1U PRIMARY KEY (ID);
  
--PRIV
GRANT SELECT, INSERT, UPDATE, DELETE ON MMOHONEY.DUMMY_TABLE_TO_AUDIT TO MMOHONEY;
