/*INSERT NEW RECORD*/
INSERT INTO MMOHONEY.DUMMY_TABLE_TO_AUDIT
            (ID,
             FIRST_NAME,
             LAST_NAME,
             START_DATE,
             END_DATE,
             IS_SALARY,
             SALARY,
             HOURLY_WAGE,
             INFORMAL_NAME,
             GENDER,
             CREATED_BY,
             CREATED_DATE,
             MODIFIED_BY,
             MODIFIED_DATE)
     VALUES( 1,'JOHN','DOE',SYSTIMESTAMP - 7,NULL,1,60000,NULL,NULL,'M','HR_EMPLOYEE_1',SYSTIMESTAMP,'HR_EMPLOYEE_1',SYSTIMESTAMP );

/*VERIFY RECORD*/
SELECT *
  FROM MMOHONEY.DUMMY_TABLE_TO_AUDIT
 WHERE ID = 1;

/*ENTITY_AUDIT RECORDS DETAILS ABOUT INSERT ON NON NULL COLUMNS*/
SELECT *
  FROM MMOHONEY.ENTITY_AUDIT
 ORDER BY TIMESTAMP DESC;

/*CANNOT UPDATE WITHOUT AUDIT FIELDS*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET INFORMAL_NAME = 'JONNY'
 WHERE ID = 1;

/*UPDATE A VARCHAR*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET INFORMAL_NAME = 'JONNY',
       MODIFIED_BY = 'HR_EMPLOYEE_2',
       MODIFIED_DATE = SYSTIMESTAMP
 WHERE ID = 1;

/*UPDATE A CHAR*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET GENDER = 'F',
       MODIFIED_BY = 'HR_EMPLOYEE_2',
       MODIFIED_DATE = SYSTIMESTAMP
 WHERE ID = 1;

/*UPDATE A NUMBER*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET SALARY = 65000,
       MODIFIED_BY = 'HR_EMPLOYEE_2',
       MODIFIED_DATE = SYSTIMESTAMP
 WHERE ID = 1;

/*UPDATE A DATE*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET END_DATE = SYSDATE,
       MODIFIED_BY = 'HR_EMPLOYEE_2',
       MODIFIED_DATE = SYSTIMESTAMP
 WHERE ID = 1;

/*UPDATE TO NULL*/
UPDATE MMOHONEY.DUMMY_TABLE_TO_AUDIT
   SET INFORMAL_NAME = NULL,
       MODIFIED_BY = 'HR_EMPLOYEE_2',
       MODIFIED_DATE = SYSTIMESTAMP
 WHERE ID = 1;

/*ENTITY_AUDIT RECORD CHANGES*/
SELECT *
  FROM MMOHONEY.ENTITY_AUDIT
 ORDER BY TIMESTAMP DESC;

/*DELETE RECORD*/
DELETE FROM MMOHONEY.DUMMY_TABLE_TO_AUDIT
 WHERE ID = 1; 
 
/*ENTITY_AUDIT RECORDS DETAILS ABOUT DELETE ON NON NULL COLUMNS*/
SELECT *
  FROM MMOHONEY.ENTITY_AUDIT
 ORDER BY TIMESTAMP DESC;
